Updates to prepare for OS X support
- Utilize new version of spede tools
- Better GUI detection

Additionally added SPEDE_SOCKET environment variable support

diff --git a/spede-run b/spede-run
--- a/spede-run
+++ b/spede-run
@@ -7,11 +7,11 @@ run_defaults=(
     [auto]=0
     [debug]=0
     [image]="build/MyOS.dli"
-    [socket]="spede.sock"
+    [socket]="${SPEDE_SOCKET:-./spede.sock}"
     [localrc]="./local.gdbinit"
     [spederc]="${spede_root}/etc/spede.gdbinit"
     [qmp]="${spede_root}/bin/qemu-qmp"
-    [dl]="${spede_root}/bin/spede-download"
+    [dl]="${spede_root}/bin/dl"
     [fs]="${spede_root}/bin/flash-sup"
     [gdb]="${spede_root}/bin/i386-elf-gdb"
     [gdb_helpers]="${spede_root}/lib/gdb_helpers.py"
@@ -62,7 +62,7 @@ function check_deps() {
     fi
 
     if [ ! -x ${run_config[gdb]} ]; then
-        echo "Error: GDB ('${run_config[gdb]}') is not executable"
+        echo "Error: GDB ('${run_config[gdb]}') is not installed or not executable"
         return 1
     fi
 }
@@ -129,8 +129,15 @@ function main() {
 
     image=${1:-${run_config[image]}}
     if [ ! -f ${image} ]; then
-	image=$(cat Makefile |grep "OS_NAME ?=" |cut -b 12-)
-	image="build/${image}.dli"
+        # Attempt to detect OS name / Image name from the Makefile
+
+        if [ -f "Makefile" ]; then
+            osname=$(cat Makefile |grep "^\s*OS_NAME" |awk -F"[?=:]+" '{ gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2 }' | head -n 1)
+
+            if [ -n "${osname}" ]; then
+                image="build/${osname}.dli"
+            fi
+        fi
 
         if [ ! -f ${image} ]; then
             echo "Image '${image}' cannot be found"
@@ -181,32 +188,37 @@ function main() {
         return 1
     fi
 
+    # Wait for the system to reset before attempting to download
+    sleep 1
+
     echo "Downloading image '${image}' to SPEDE Target via ${tty}..."
-
-
-    if [ ${run_config[debug]} -eq 0 ]; then
-        ${run_config[dl]} ${image} ${tty}
-        if [ $? -ne 0 ]; then
-            echo "Error: Unable to download image '${image}' to the SPEDE Target"
-            return 1
-        fi
-
-        return 0
-    else
-        ${run_config[dl]} -g ${image} ${tty}
-        if [ $? -ne 0 ]; then
-            echo "Error: Unable to download image '${image}' to the SPEDE Target"
-            return 1
-        fi
+    ${run_config[dl]} ${tty} ${image}
+    if [ $? -ne 0 ]; then
+        echo "Error: Unable to download image '${image}' to the SPEDE Target"
+        return 1
     fi
 
-#    echo "Enabling GDB..."
-#    ${run_config[fs]} ${tty} e
-#    if [ $? -ne 0 ]; then
-#        echo "Error: Unable to enable GDB on the SPEDE Target"
-#        return 1
-#    fi
-#    sleep 1
+    sleep 1
+    if [ ${run_config[debug]} -eq 0 ]; then
+        # Execute the image and run it without GDB enabled
+
+        echo "Executing the image '${image}' on the SPEDE Target"
+        ${run_config[fs]} -r ${tty}
+        if [ $? -ne 0 ]; then
+            echo "Error: Unable to execute the image '${image}' on the SPEDE Target"
+            return 1
+        fi
+
+        # No need to continue further for GDB
+        return 0
+    fi
+
+    echo "Executing the image '${image}' on the SPEDE Target with GDB Enabled"
+    ${run_config[fs]} -g ${tty}
+    if [ $? -ne 0 ]; then
+        echo "Error: Unable to execute the image '${image}' on the SPEDE Target with GDB Enabled"
+        return 1
+    fi
 
     cmd_spederc=
     cmd_localrc=
